// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-Jh9ZnBKcU74vW5NXRrhQG4gLyNyd8M',
    appId: '1:82451100665:web:7f3368e7164daa2ded8328',
    messagingSenderId: '82451100665',
    projectId: 'holbegram-48a78',
    authDomain: 'holbegram-48a78.firebaseapp.com',
    storageBucket: 'holbegram-48a78.appspot.com',
    measurementId: 'G-3C1BYV0VVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9osKLAqHMVcZ4hlJqkPx-Rx3q-lYixQ',
    appId: '1:82451100665:android:a74e38839d9ade8bed8328',
    messagingSenderId: '82451100665',
    projectId: 'holbegram-48a78',
    storageBucket: 'holbegram-48a78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZldRfNe2a5LMk-vxDfp2Gthy-SroQvEU',
    appId: '1:82451100665:ios:0b9209f970bebb34ed8328',
    messagingSenderId: '82451100665',
    projectId: 'holbegram-48a78',
    storageBucket: 'holbegram-48a78.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZldRfNe2a5LMk-vxDfp2Gthy-SroQvEU',
    appId: '1:82451100665:ios:320a1c22f1e64166ed8328',
    messagingSenderId: '82451100665',
    projectId: 'holbegram-48a78',
    storageBucket: 'holbegram-48a78.appspot.com',
    iosBundleId: 'com.example.holbegram.RunnerTests',
  );
}
